// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearArticles = `-- name: ClearArticles :exec
DELETE FROM articles
`

func (q *Queries) ClearArticles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearArticles)
	return err
}

const getArticlesByFeedId = `-- name: GetArticlesByFeedId :many
SELECT id, created_at, updated_at, name, description, feed_url, feed_id, publish_date, last_fetched_at FROM articles WHERE feed_id = $1
`

func (q *Queries) GetArticlesByFeedId(ctx context.Context, feedID uuid.UUID) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByFeedId, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.FeedUrl,
			&i.FeedID,
			&i.PublishDate,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (id, created_at, updated_at, name, feed_url, feed_id, publish_date, last_fetched_at, description)
VALUES(
          $1,
          $2,
          $3,
          $4,
          $5,
          $6,
          $7,
          $8,
          $9
      )
`

type InsertArticleParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	FeedUrl       string
	FeedID        uuid.UUID
	PublishDate   time.Time
	LastFetchedAt time.Time
	Description   string
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertArticle,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.FeedUrl,
		arg.FeedID,
		arg.PublishDate,
		arg.LastFetchedAt,
		arg.Description,
	)
	return err
}
